//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_to_user
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int eventId { get; set; }
        public int groupId { get; set; }
    
        public virtual user user { get; set; }
        public virtual group group { get; set; }
        public virtual @event @event { get; set; }
    }
}
